name: Install Python and required modules
on: [push, pull_request]

jobs:
 # python installtion
  install-python:
  # should run on linux based operating system
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt 
    - run: |
        python downloads/add_to_content_htm_1a.py
        python downloads/add_to_content_htm_1b.py
        python downloads/generate_pages.py


